Controllers/AuctionsController.cs
using System.IO;
using System.Linq;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using AuctionCore.Models.Auction;
using AuctionCore.Models.Session;
using AuctionCore.Data.Services;
using AuctionCore.Utils.Extensions;

namespace AuctionCore.Controllers
{
    public class AuctionsController : Controller
    {
        private readonly IAuctionService _auctions;

        private readonly ICategoryService _categories;

        private readonly ISessionService _sessions;

        public AuctionsController(
            IAuctionService auctions, ICategoryService categories, ISessionService sessions)
        {
            _auctions = auctions;
            _categories = categories;
            _sessions = sessions;
        }

        [HttpGet("/Auctions")]
        public IActionResult Auctions(
            string category, string range, string search, string orderBy)
        {
            List<Auction> auctions = _auctions.GetAll();
            ViewData["categories"] = _categories.GetAll();

            if (category != null)
            {
                string[] categories = category.ToLower().Split(".");

                // only primary category has been specified
                if (categories.Length == 1)
                {
                    auctions = auctions.FindAll(a => a.Item.Category.Primary.ToLower().StripNonLetters() == categories[0]);
                }
                // primary and secondary category has been specified
                else if (categories.Length == 2)
                {
                    auctions = auctions.FindAll(a => a.Item.Category.Primary.ToLower().StripNonLetters() == categories[0] && 
                    a.Item.Category.Secondary.ToLower().StripNonLetters() == categories[1]);
                }
            }

            if (range != null)
            {
                string[] split = range.Split('-');

                if (split.Length == 2 || split.Length == 3)
                {
                    split[split.Length - 1] = split[split.Length - 1] == "&#8734;" ? double.MaxValue.ToString() : split[split.Length - 1];

                    if (double.TryParse(split.Length == 2 ? split[0] : split[1], out double lower) &&
                        double.TryParse(split.Length == 2 ? split[1] : split[2], out double upper))
                    {
                        auctions = auctions.MyRange(lower, upper, split.Length == 2 ? "startingprice" : split[0]).ToList();
                    }
                }
            }

            if (search != null)
            {
                auctions = auctions.FindAll(auc => auc.Item.Name.ToLower() == search.ToLower());
            }

            if (orderBy != null)
            {
                string[] order = orderBy.ToLower().Split(".");
                auctions = auctions.MyOrderBy(order[0], order.Length == 2 && order[1] == "desc" ? false : true).ToList();
            }

            return View(auctions);
        }

        [HttpGet("/Create")]
        public IActionResult Create(string orderBy)
        {
            if (_sessions.Exists(HttpContext, "session:id", out Session session) && session.Username != null)
            {
                ViewData["categories"] = _categories.GetAll();
                ViewData["auctions"]   = _auctions.GetAll().FindAll(auc => auc.Auctioneer == session.Username);

                if (orderBy != null)
                {
                    string[] order = orderBy.ToLower().Split(".");
                    bool asc = order.Length == 2 && order[1] == "desc" ? false : true;

                    ViewData["auctions"] = ((List<Auction>)ViewData["auctions"]).MyOrderBy(order[0], asc);
                }
                return View();
            }
            return RedirectToAction("Index", "Home");
        }

        [ValidateAntiForgeryToken]
        [HttpPost("/Create")]
        public IActionResult Create(Auction auction)
        {
            if (_sessions.Exists(HttpContext, "session:id", out Session session) && session.Username != null)
            {
                ViewData["categories"] = _categories.GetAll();
                ViewData["auctions"]   = _auctions.GetAll().FindAll(auc => auc.Auctioneer == session.Username);

                if (ModelState.IsValid)
                {
                    if (auction.Item.ImageFiles != null)
                    {
                        foreach (IFormFile file in auction.Item.ImageFiles)
                        {
                            var binaryReader = new BinaryReader(file.OpenReadStream());
                            byte[] data = binaryReader.ReadBytes((int)file.Length);
                            binaryReader.Close();
                            auction.Item.Images.Add(new Image { Data = data, ContentType = file.ContentType });
                        }
                    }
                    auction.Auctioneer = session.Username;
                    _auctions.Insert(auction);
					_categories.IncrementCount(auction.Item.Category.Primary, auction.Item.Category.Secondary);
                    return RedirectToAction("Create");
                }
                return View(auction);
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

Views/Shared/_HeaderNavBar.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AuctionCore</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Auctions" asp-action="Auctions">Auctions</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Auctions" asp-action="Create">Create</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>

                <li>

                    <button type="button" class="btn btn-info" id="modalBtn"
                            style="position: absolute; right: 20px;">
                        User Profile
                    </button>

                    <div id="login-modal" class="modal hide" role="dialog">

                        <div class="modal-dialog">

                            <div class="modal-content">

                                <div class="modal-header">
                                    <button type="button" class="close float-right modal-close">&times;</button>
                                </div>

                                <div class="modal-body">
                                    <div id="login-wrapper">
                                        <div class="row">
                                            <div class="col-md-12">
                                                @Html.AntiForgeryToken()
                                                <form method="post" class="form-login">
                                                    <div class="form-group">
                                                        <h4 class="modal-title text-center text-dark">Sign in</h4>
                                                    </div>

                                                    <div class="form-group">
                                                        <input type="email" id="emailaddress" name="email" class="form-control" placeholder="Email address" required autofocus>
                                                        <span class="text-danger"></span>
                                                    </div>

                                                    <div class="form-group">
                                                        <input type="password" id="password" name="password" class="form-control" placeholder="Password" required>
                                                        <span class="text-danger"></span>
                                                    </div>

                                                    <div class="form-group">
                                                        <button type="submit" class="btn btn-lg btn-primary btn-block text-uppercase">Sign in</button>
                                                    </div>

                                                    <div class="form-group">
                                                        <a href="#" style="padding-right: 10px;">Forgot Password?</a>
                                                        <a href="#">Not Registered?</a>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div id="account-modal" class="modal hide" role="dialog">

                        <div class="modal-dialog">

                            <div class="modal-content">

                                <div class="modal-header">
                                    <button type="button" class="close float-right modal-close">&times;</button>
                                </div>

                                <div class="modal-body">
                                    <div id="account-wrapper">

                                        <div class="form-group">
                                            <h4 class="modal-title text-center text-dark">Account</h4>
                                        </div>

                                        <div class="form-group">
                                            <p class="text-dark"></p>
                                        </div>

                                        <div class="row">
                                            <div class="form-group" style="margin: 0 auto;">
                                                <button type="button" class="btn btn-primary">Settings</button>
                                                <button id="logoutBtn" type="button" class="btn btn-danger">Logout</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

Views/Shared/_Layout.cshtml
@using  AuctionCore.Data.Services
@inject AuctionCore.Data.Services.ISessionService SessionService

@using  Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AuctionCore</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/fontawesome/css/all.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/account-widget.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/css/ion.rangeSlider.min.css" />
</head>

<body>
    <header>
        <partial name="_HeaderNavBar"/>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/lib/fontawesome/js/all.js"></script>
        <script src="~/js/site.js"></script>
        <script src="~/js/ajax.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/js/ion.rangeSlider.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>